### ISSUE TITLE
Missing 🤨  and  🦟  emojis

### ISSUE THREAD

**Issue by silvadenisaraujo** [NeelShah18/emot#18]
**Describe the bug**
In the emot dictionary it's missing two emojis, 🤨   and 🦟   , respectively the unicodes (U+1F928, U+1F99F)

**To Reproduce**
```python
def convert_emojis(text):
    for emot in UNICODE_EMO:
        text = text.replace(emot, "_".join(UNICODE_EMO[emot].replace(",","").replace(":","").split()))
    return text

convert_emojis('Hello 🤨')
```

**Expected behavior**
'Hello :face_with_raised_eyebrow: '

**Additional context**
The same example applies to the mosquito emoji.

**Comment by NeelShah18** [comment]
@silvadenisaraujo Thank you for the contribution and using it. I will add this emoji this week and will avilable from next week. aplogies for late reply.

Again thank you for contribution and support.

**Comment by NeelShah18** [comment]
added in new version 3.0 branch. Planning to release this week.
