### ISSUE TITLE
Inconsistent output types obtained

### ISSUE THREAD

**Issue by sacrosanct007** [NeelShah18/emot#21]
**Describe the bug**
The use of emot (version 2.1) provides inconsistent output. It provides list in some case and dictionary in some other cases.

**To Reproduce**

```
emoticon_details_1=emot.emoticons("The weather is ☁️ :), we might need to carry our ☂️ :(")    
emoticon_details_2=emot.emoticons("Cooool :)")   
print(type(emoticon_details_1))    
print(type(emoticon_details_2))

```

**Expected behavior**
The output type should be dictionary in all cases.

**Comment by NeelShah18** [comment]
@sacrosanct007 

Can you please confirm it is happening with latest release as well :

https://github.com/NeelShah18/emot/tree/v2.2

Latest release is v2.2.

Appreciate your feedback and active participation for bug reporting.

Good day.

Thank you
