### ISSUE TITLE
Inconsistent Results

### ISSUE THREAD

**Issue by RavishWorld** [NeelShah18/emot#22]
**Describe the bug**
For very similar string's I am getting different results

**To Reproduce**
a = "I love python :)"
> {'value': [':)'], 'location': [[14, 16]], 'mean': ['Happy face or smiley'], 'flag': True}

a = "This is  :)"
> {'value': [':)'], 'location': [[9, 11]], 'mean': ['Happy face or smiley'], 'flag': True}

a = "This story is great :)"
> {'value': [':)'], 'location': [[20, 22]], 'mean': ['Happy face or smiley'], 'flag': True}

a = "This story is good :)"
> [{'flag': False}]

**Expected behavior**
I was expecting a True flag for all of them. 

Thank you NeelShah for this wonderful lib.

**Comment by NeelShah18** [comment]
@RavishWorld  Can you please confirm it is happening with latest release as well : 

https://github.com/NeelShah18/emot/tree/v2.2

Latest release is v2.2.

Appreciate your feedback and active participation for bug reporting. 

Good day.

Thank you

**Comment by RavishWorld** [comment]
Hi,

No, it's not working.
Can you please help? 
I was going through your pull request -> is it because of #20 Bump the setup.py to the 2.2 issues?
or my lack of knowledge.

Thank you so much for your prompt response.

**Comment by mrzzy** [comment]
Only version `2.1` seems the only latest to be hosted on Pypi with `pip install emot`.
Using the latest `v2.2` tag:
-  I can install directly from the Github repository with `pip install --upgrade git+https://github.com/NeelShah18/emot.git@v2.2`
- But `pip freeze` still reports that its `2.1`. I guess this is related to PR #20.
- Installing from straight `master` seems to fix the issue `pip install --upgrade git+https://github.com/NeelShah18/emot.git@master`

**Comment by NeelShah18** [comment]
@mrzzy  Thank you for that. I will merge the change. Really appreciate your help for support and encroachment.

Thank you @mrzzy  and @RavishWorld  :-)
