### ISSUE TITLE
The regex for the "(?_?)" emoticon is wrong, it just matches ")"  

### ISSUE THREAD

**Issue by Ronserruya** [NeelShah18/emot#23]
Im not sure this library is maintained, seeing as the last release is from 2018, but anyway

The current regex that is used is `"\(?_?\)"`, the question marks are not escaped so` "(?_?)"` is never matched, in addition, this also causes ")" to be matched

Just need to change it to `"\(\?_\?\)"`

Note that a question mark needs to be escaped since in regex a question mark means that the previous character is optional

**Comment by NeelShah18** [comment]
It is fix in new version 3.0 version. You can try new 3.0 version from branch. I will launch new version this week.
