### ISSUE TITLE
Getting error while using the latest version

### ISSUE THREAD

**Issue by anantaarora** [NeelShah18/emot#32]
Hi,
I am facing an issue while upgrading to the latest emot version:
This is my import statement
from emot.emo_unicode import UNICODE_EMO, EMOTICONS

Error:
ImportError: cannot import name 'UNICODE_EMO' from 'emot.emo_unicode' (/usr/local/lib/python3.7/dist-packages/emot/emo_unicode.py)

Please help

**Comment by NeelShah18** [comment]
Hello @anantaarora  thank you for issue. Did you try 3.1 version?

**Comment by Keerthan28** [comment]
still getting the same error

**Comment by anantaarora** [comment]
I had resolved this error by making following changes:
from emot.emo_unicode import UNICODE_EMOJI


Thanks

**Comment by Keerthan28** [comment]
> I had resolved this error by making following changes:
> from emot.emo_unicode import UNICODE_EMOJI
> 
> Thanks

what about emoticons. I'm getting the same error for emoticons

**Comment by NeelShah18** [comment]
Let me check I think try and catch us is not working as expected for loading of the other library.

**Comment by NeelShah18** [comment]
@anantaarora , @Keerthan28 :

I created a new virtual environment in a totally new mac system and did the fresh install. Then I try to perform the basic testing and everything works normally. Can you please share how I can replicate the issue?
<img width="1439" alt="Screen Shot 2021-08-02 at 12 14 01 PM" src="https://user-images.githubusercontent.com/18536531/127892716-861396cb-62ea-438b-9cfd-67b3beee2f6e.png">
<img width="1439" alt="Screen Shot 2021-08-02 at 12 18 00 PM" src="https://user-images.githubusercontent.com/18536531/127892735-fff83ea5-b1bc-49b2-b79e-49fe21f97ef5.png">

**Comment by SajibKumar** [comment]
> I had resolved this error by making following changes:
> from emot.emo_unicode import UNICODE_EMOJI
> 
> Thanks

Actually, it doesn't work. I don't see any change in my dataset after the emoticon conversion. Even I had resolved this error like you.

**Comment by SajibKumar** [comment]
![image](https://user-images.githubusercontent.com/43386136/129445151-fe1fbd21-8980-4188-a8b3-4097a2b358b3.png)
![image](https://user-images.githubusercontent.com/43386136/129445158-3eb00ce0-2baf-4b5a-a85c-ffa573541954.png)
This code isn't working for me, Please help me to sort out the problem.

**Comment by NeelShah18** [comment]
@SajibKumar  It is error with mismatching of bracts.
![Screenshot from 2021-08-14 13-22-22](https://user-images.githubusercontent.com/18536531/129455398-59e29e37-93ca-468b-88ab-d7e6eaaebe22.png)

**Comment by NeelShah18** [comment]
@SajibKumar  Please check the all code you put in the correct bracts level.

**Comment by SajibKumar** [comment]
> @SajibKumar It is error with mismatching of bracts.
> ![Screenshot from 2021-08-14 13-22-22](https://user-images.githubusercontent.com/18536531/129455398-59e29e37-93ca-468b-88ab-d7e6eaaebe22.png)

But this code is working fine before updating the emot library.

**Comment by SajibKumar** [comment]
> @SajibKumar Please check the all code you put in the correct bracts level.

I think all brackets are okay.

**Comment by SajibKumar** [comment]
But there are no mismatching brackets. This code is working fine for me
before the Update. Please help to solve this problem, thank you.

**Comment by NeelShah18** [comment]
@SajibKumar 

Error shows in the code are regarding unbalanced bracket position. It can have two possibilities:

1) https://stackoverflow.com/questions/10318248/unbalanced-parenthesis-python
2) https://www.geeksforgeeks.org/check-for-balanced-parentheses-in-python/

Can you please check the issue. If you can share more detail what you want try to do, we can help you.

Thank you,
Neel

**Comment by topekekere** [comment]
ModuleNotFoundError: No module named 'emot.emo_unicode'

![Screenshot from 2021-10-11 15-23-56](https://user-images.githubusercontent.com/52776421/136797637-c0173b9a-e8e5-45ff-ab2f-77840141724b.png)

**Comment by nu8buster** [comment]
I am still getting an error like this. Could you please check @NeelShah18?
![image](https://user-images.githubusercontent.com/93789457/141911823-41092bbf-f345-4869-8eea-6818f951d5a8.png)
