### ISSUE TITLE
EMOTICON cannot be imported

### ISSUE THREAD

**Issue by nu8buster** [NeelShah18/emot#36]
While importing the "EMOTICON" library, it is not importing

![image](https://user-images.githubusercontent.com/93789457/141913845-c95656ed-a4b6-4c9b-8e20-c644f3064bee.png)

**Comment by NeelShah18** [comment]
@nu8buster we no longer have emoticons. we change the name to EMOTICONS_EMO . Please open the file emot --> emo_unicode.py file for more details.

link: https://github.com/NeelShah18/emot/blob/master/emot/emo_unicode.py#L9

**Comment by NeelShah18** [comment]
@nu8buster  Please open the issue again if you have any other questions.
