### ISSUE TITLE
Plz use MIT or Apache2.0 Licence

### ISSUE THREAD

**Issue by pokecheater** [NeelShah18/emot#41]
Instead of GPL so people can use this library in productive environments.

By the way parts of your library was copycatted by a kaggle notebook (this is how I was directed to this page). But this notebook is not licenced under GPL3 (which it should since every reuse of gpl in another program will force that program also to be licenced under gpl3). Instead they use Apache 2.0. So strictly they already violate your licence terms. So plz change to MIT or APache2.0 if you want that people can freely use your library without restrictions.

Greetings :)

PS: By the way good job (Y)

**Comment by pokecheater** [comment]
https://www.kaggle.com/code/sudalairajkumar/getting-started-with-text-preprocessing/notebook Here is the link to the notebook which violates your GPL3-terms.

Summarize of gpl3 https://www.youtube.com/watch?v=sQIVclmxvdQ

**Comment by NeelShah18** [comment]
Thank you for the suggestion. And i agree with you. I am changing the license to MIT.
