### ISSUE TITLE
Only letter emojis

### ISSUE THREAD

**Issue by pasqLisena** [NeelShah18/emot#5]
The module extracts 'oo' as emoticon in words like 'school', 'loop', and 'xp' in 'express', 'experience'

**Comment by NeelShah18** [comment]
I will see and get back to you thanks for the bug

**Comment by NeelShah18** [comment]
Every emoji to word is not possible because it is a meaningful word too. But you can use reverse emoji function to get the meaning. It is updated in new release.

**Comment by pasqLisena** [comment]
mmm your answer seems to be to another question :)

Should your library detect 'xp' inside the world 'express' ? or should let it go?

**Comment by NeelShah18** [comment]
Nop. It doesn't not check 'xp' in express.

**Comment by NeelShah18** [comment]
It is not feasible with my current knowledge as it is extremely hard to know xp is emoji or operating system. It is linguistic limitation of hard coded system. We need advance AI to resolve this issue.
