### ISSUE TITLE
Stronger emoticons

### ISSUE THREAD

**Issue by pasqLisena** [NeelShah18/emot#8]
`:-))))))` (very happy) or `:-((((` (very sad) are not recognised.

**Comment by NeelShah18** [comment]
Thanks, @pasqLisena  for the bug i will fix this weekend and it is ready to go.

**Comment by NeelShah18** [comment]
Hey @pasqLisena , Can you tell me here :-)))) the sign ")" is any number of time means it vary right?

**Comment by NeelShah18** [comment]
sorry for the late reply. But I check all different possibilities and provide dynamic way to add emoji in new 3.0 version so user can add as many different type of emoji they want.
